ROOTDIR: r'C:\Users\Marconi\Young Lab Dropbox\Young Group\THz\Raw Data'
DATADIR: '2023_10_02_AKN_BLG_04'
FILENAME: "gate_sweep"

DEPENDENTS:
- DELAY_IDX
- DELAY [MM]
- SWEEP
- V_GATE [V]
INDEPENDENTS:
- THz X [A]
- THz Y [A]
- Transport X [A]
- Transport Y [A]
- Temp D4 [K]
- Temp D5 [K]

LIA_THZ:
  TIME_CONST: 0.3
  SENS: 20.0e-3

LIA_TRANSPORT:
  TIME_CONST: 0.3
  SENS: 100.0e-6
  FREQ: 113.777
  AMP: 1.0

DAC_DATA: DAC-ADC_AD7734-AD5791 (COM5)
DAC_CONV_TIME: 500
SAMPLING: 0.1
AVGS: 100

SWEEPS: 3
GAIN: 100000000.0

V_GATE_CH: 1
DAC_IN_CH:
- 0
- 1
- 6
- 7

V_GATE_I: -1.0
V_GATE_F: 1.0
V_GATE_STEPS: 400

DELAY_I: 27.0
DELAY_F: 32.0
DELAY_STEPS: 21
DELAY_STEP_LIST:
- 28.59
- 28.91
- 29.02
- 29.08
- 29.16
- 29.24
- 29.58
- 29.68
- 29.75
- 29.85
- 29.95