ROOTDIR: r'C:\Users\Marconi\Young Lab Dropbox\Young Group\THz\Raw Data'
DATADIR: '2023_07_19_AKN_DMLG_08'
FILENAME: "MirrorScanDAC"
SPOT: 'A'

E:
  X_CENTER: 5.4440
  Y_CENTER: 0.1765
  DAC_D_OUT_CH: 0
  DAC_D_IN_CH: 6
  RANGE: 0.05
  STEP: 0.001
A:
  X_CENTER: 0.948
  Y_CENTER: 0.5570
  DAC_D_OUT_CH: 0
  DAC_D_IN_CH: 1
  RANGE: 0.05
  STEP: 0.001

SWEEPS: 1
AUTOZOOM: 1

DAC_DATA: DAC-ADC_AD7734-AD5791 (COM5)
DAC_D_DUMMY_CH: 3

AVGS: 1
SAMPLING: 1
READINGS: 1

DAC_MIRROR: DAC-ADC_AD7734-AD5791_4x4 (COM3)
DAC_M_CH:
- 0         # X - E
- 1         # Y - E
- 2         # X - A
- 3         # Y - A

BIAS: 10.0
DELAY: 0.1


