ROOTDIR: r'C:\Users\Marconi\Young Lab Dropbox\Young Group\THz\Raw Data'
DATADIR: '2023_07_05_TeraLine'
FILENAME: "MirrorScanDAC"

EX_CENTER: 5.748   
EY_CENTER: -0.594
AX_CENTER: 1.246
AY_CENTER: 0.478
RANGE: 0.1
STEP: 0.002

DAC_DATA: DAC-ADC_AD7734-AD5791 (COM5)
DAC_D_CH: 7
DAC_D_DUMMY_CH: 3

AVGS: 10
SAMPLING: 1
READINGS: 10

DAC_MIRROR: DAC-ADC_AD7734-AD5791_4x4 (COM3)
DAC_M_CH:
- 0         # X
- 1         # Y

BIAS: 10
DELAY: 0.1


