ROOTDIR: C:\Users\Marconi\Young Lab Dropbox\Young Group\THz\Raw Data
DATADIR: '2024_08_13_TL2840'
FILENAME: MScanSMU
  
EY_CENTER: 0.9880         #DAC1 refl: -0.4510; trans: -0.35
EX_CENTER: -0.1370         #DAC0 refl: 5.8450; trans: 6.25 # 5.9750 
AY_CENTER: 0.6740        #DAC3 (old: 0.8700)
AX_CENTER: 0.6990        #DAC2 (old: 0.7350)
RANGE: 0.01              # usual: 0.2
STEP: 0.001               # usual: 0.01

DAC_DATA: DAC-ADC_AD7734-AD5791 (COM5)         # DAC for signal
DAC_MIRROR: DAC-ADC_AD7734-AD5791_4x4 (COM3)   # DAC for mirrors
DAC_CH_Y: 1
DAC_CH_X: 0

BIAS: 10
DELAY: 0.05
SMU_RANGE: 100e-6         # current range on K2450

COMPL: 20e-6
NPLC: 1                  # 0.1 -- 10
FILT: OFF              # 'ON' or 'OFF'
FILT_TYPE: REPeat      # 'REPeat' or 'MOVing'
FILT_COUNT: 1            # 1 -- 100

AUTOZOOM: False
ZOOM_FACTOR: 2