ROOTDIR: r'C:\Users\Marconi\Young Lab Dropbox\Young Group\THz\Raw Data'
DATADIR: '2023_03_28'
FILENAME: "MirrorScanDAC"
SPOT: 'E'

E:
  X_CENTER: 5.3375    # DAC 0
  Y_CENTER: -0.4320   # DAC 1
  DAC_D_OUT_CH: 0
  DAC_D_IN_CH: 6
  RANGE: 0.02
  STEP: 0.001
A:
  X_CENTER: 1.1095    # DAC 2
  Y_CENTER: 0.7125    # DAC 3
  DAC_D_OUT_CH: 0
  DAC_D_IN_CH: 1
  RANGE: 0.02
  STEP: 0.001

SWEEPS: 1
AUTOZOOM: 1
STAGE_POS: 21.7

DAC_DATA: DAC-ADC_AD7734-AD5791 (COM5)
DAC_OUTPUT_CH_DUMMY: 
- 3

AVGS: 100
SAMPLING: 1
READINGS: 5

DAC_MIRROR: DAC-ADC_AD7734-AD5791_4x4 (COM3)
DAC_M_CH:
- 0         # X - E
- 1         # Y - E
- 2         # X - A
- 3         # Y - A

BIAS: 10.0
DELAY: 0.1

LIA:
  SENS: 100.0e-3
  TIME_CONST: 0.01
