MEASURE_MODE: FAST
ROOTDIR: C:\Users\Marconi\Young Lab Dropbox\Young Group\THz\Raw Data
DATADIR: 2024_02_21_AKNDB27_1A
FILENAME: transient

DEPENDENTS:
- delay_mm
- delay_ps
INDEPENDENTS:
- Lockin X [A]
- Lockin Y [A]
- Input 2 [V]
- Input 3 [V]
- Input 4 [V]
- Input 6 [V]
- Input 7 [V]
- Temp A [K]
- Temp B [K]

DELAY_RANGE_MM:
- 24.5                # Full: 24; Sample: 24
- 34.5                # Full: 34; Sample: 30
DELAY_TRAVEL: 10
DELAY_POINTS: 1001
DAC_TIME: 55       # 230 s for 5000 pt

LIA:
  TIME_CONST: 0.1
  SENS: 0.005

V_GATE_I: -1.0
V_GATE_F: 1.0
V_GATE_STEPS: 10
V_GATE_CH: 1

T_INITIAL: 95.0
T_FINAL: 120.0
T_STEPS: 5

SWEEPS: 10
AVGS: 5
FPOINTS: 3000
SAMPLING: 0.1
READINGS: 1

GAIN: 100000000.0
BIAS_E: 10.0
BIAS_AB: 0.0

MAX_I_E: 0
MAX_I_AB: 0

MIRROR_SCAN: 0
MSWEEPS: 1
MAVGS: 1
STAGE_POS: 21.774 # 21.7; 22.55; 25.0
E:
  X_CENTER: 5.2140
  Y_CENTER: -0.6300
  DAC_D_OUT_CH: 0
  DAC_D_IN_CH: 6
  RANGE: 0.005
  STEP: 0.0002
A:
  X_CENTER: 1.2375
  Y_CENTER: 0.6180
  DAC_D_OUT_CH: 0
  DAC_D_IN_CH: 1
  RANGE: 0.005
  STEP: 0.0002

DAC_DATA: DAC-ADC_AD7734-AD5791 (COM5)
DAC_CONV_TIME: 500
DAC_OUTPUT_CH: 0
DAC_OUTPUT_CH_DUMMY:
- 3
DAC_INPUT_CH:
- 0
- 1
- 2
- 3
- 4
- 6
- 7
DAC_MIRROR: DAC-ADC_AD7734-AD5791_4x4 (COM3)
DAC_M_CH:
- 0         # X - E
- 1         # Y - E
- 2         # X - A
- 3         # Y - A
DAC_CH_Y: 1
DAC_CH_X: 0
DELAY: 0.1