MEASURE_MODE: FAST
ROOTDIR: C:\Users\Marconi\Young Lab Dropbox\Young Group\THz\Raw Data
DATADIR: 2023_07_05_TeraLine
FILENAME: transient

DEPENDENTS:
- delay_mm
- delay_ps
INDEPENDENTS:
- Lockin X [A]
- Lockin Y [A]
- Input 2 [V]
- Input 3 [V]
- Input 5 [V]
- Input 6 [V]
- Temp A [K]
- Temp B [K]

DELAY_RANGE_MM:
- 21
- 31
DELAY_TRAVEL: 10
DELAY_POINTS: 1001
DAC_TIME: 308.0
STAGE_VEL: 0.032467532467532464

TIME_CONST: 0.01
SENS: 0.1

V_GATE_I: 0
V_GATE_F: 0
V_GATE_STEPS: 1

T_INITIAL: 95.0
T_FINAL: 120.0
T_STEPS: 5

SWEEPS: 1
AVGS: 200
FPOINTS: 10000
SAMPLING: 0.1
READINGS: 5

GAIN: 100000000.0
BIAS_E: 10
BIAS_AB: 0.0
SMU_RANGE: 1.0e-06
MAX_I_E: 0
MAX_I_AB: 0
NPLC: 1
FILT: 'OFF'
FILT_TYPE: REPeat
FILT_COUNT: 1
MIRROR_SCAN: 1
EY_CENTER: -0.323
EX_CENTER: 5.783
AY_CENTER: 0.478
AX_CENTER: 1.246
RANGE: 0.2
STEP: 0.01
DAC_DATA: DAC-ADC_AD7734-AD5791 (COM5)
DAC_CONV_TIME: 500
DAC_OUTPUT_CH: 0
DAC_OUTPUT_CH_DUMMY:
- 3
DAC_INPUT_CH:
- 0
- 1
- 2
- 3
- 6
- 7
DAC_MIRROR: DAC-ADC_AD7734-AD5791_4x4 (COM3)
DAC_CH_Y: 1
DAC_CH_X: 0
DELAY_MEAS: 0.1