ROOTDIR: C:\Users\Marconi\Young Lab Dropbox\Young Group\THz\Raw Data
DATADIR: '2024_08_20_AKNDB32_2B'
FILENAME: transient

DEPENDENTS:
- sweep_num
- n0 idx
- p0 idx
- delay_mm
- delay_ps
- n0
- p0
- vb
- vt
INDEPENDENTS:
- Lockin X [A]
- Lockin Y [A]
- Input 2 [V]
- Input 3 [V]
- Input 4 [V]
- Input 5 [V]
- Input 6 [V]
- Stage Flag [V]
- Temp A [K]
- Temp B [K]

MEASURE_MODE: FAST # FAST or SLOW
DELAY_RANGE_MM:
- 36.6                # Full: 60.5; Sample: X With piezo change to 30-35
- 38.6                 # Full: 70.5; Sample: X
DELAY_TRAVEL: 10
DELAY_POINTS: 101
DELAY_POS_THZ: 25.26  # peak THz signal
DAC_TIME: 135.0         # 135s for 2000 pts

LIA_THZ:
  DEV: desktop-marconi GPIB Bus - GPIB0::8::INSTR
  TIME_CONST: 0.1
  SENS: 20.0e-3

LIA_THZ2:
  DEV: desktop-marconi GPIB Bus - GPIB0::7::INSTR
  TIME_CONST: 0.1
  SENS: 1.0e-3
  AMPL: 150.0e-3
  FREQ: 37.7777

LIA_R:
  DEV: desktop-marconi GPIB Bus - GPIB0::4::INSTR
  TIME_CONST: 0.1
  SENS: 100.0e-3
  AMPL: 00.0e-3
  FREQ: 87.7777

SWEEPS: 1
AVGS: 10
FPOINTS: 2000
SFPOINTS: 1
SAMPLING: 0.5
READINGS: 1

MEAS_PARAMS:
  n0_PNTS: 1
  p0_PNTS: 1
  n0_RANGE:     # fast axis
    - 0.0
    - 0.0
  p0_RANGE:     # slow axis
    - -0.0
    - -0.0
  DELTA: 0.2   # gate asymmetry

  MAX_vb: 4.0
  MAX_vt: 2.0   # 
  MIN_vb: -4.0
  MIN_vt: -2.1  # 

V_GATE_TOP_CH: 1    # slow axis
V_GATE_TOP_PNTS: 1
V_GATE_TOP_RNG:
  - -0.0
  - 0.0

V_GATE_BOT_CH: 2    # fast axis
V_GATE_BOT_PNTS: 5  
V_GATE_BOT_RNG:
  - -1.0
  - 1.0

T_INITIAL: 95.0
T_FINAL: 120.0
T_STEPS: 5

GAIN: 100000000.0
BIAS_E: 10.0
BIAS_AB: 0.0
IAC: 10.0e-9

MAX_I_E: 0
MAX_I_AB: 0

MIRROR_SCAN: 0
MSWEEPS: 1
MAVGS: 1
STAGE_POS: 21.774 # 21.7; 22.55; 25.0
E:
  X_CENTER: 5.2140
  Y_CENTER: -0.6300
  DAC_D_OUT_CH: 0
  DAC_D_IN_CH: 6
  RANGE: 0.005
  STEP: 0.0002
A:
  X_CENTER: 1.2375
  Y_CENTER: 0.6180
  DAC_D_OUT_CH: 0
  DAC_D_IN_CH: 1
  RANGE: 0.005
  STEP: 0.0002

DAC_DATA: DAC-ADC_AD7734-AD5791 (COM5)
DAC_CONV_TIME: 250
DAC_OUTPUT_CH: 0        # Bias E
DAC_OUT_CH:
  - 1                   # top gate
  - 2                   # bottom gate
DAC_OUTPUT_CH_DUMMY:
  - 3
DAC_INPUT_CH:
  - 0         # THz LX
  - 1         # THz LY
  - 2         # Transport LX 
  - 3         # Transport LY
  - 4         #
  - 5         #
  - 6         # Optical Encoder
  - 7         # Stage flag
DAC_MIRROR: DAC-ADC_AD7734-AD5791_4x4 (COM3)
DAC_M_CH:
  - 0         # X - E
  - 1         # Y - E
  - 2         # X - A
  - 3         # Y - A
DAC_CH_Y: 1
DAC_CH_X: 0
DELAY: 0.1