ROOTDIR: r'C:\Users\Marconi\Young Lab Dropbox\Young Group\THz\Raw Data'
DATADIR: '2023_11_21_AKN_MLG_07'
FILENAME: "transport"

DEPENDENTS:
- SWEEP
- V_GATE
INDEPENDENTS:
- Lockin X [A]
- Lockin Y [A]
- Temp D4 [K]
- Temp D5 [K]

LIA:
  TIME_CONST: 0.3
  SENS: 100.0e-6
  FREQ: 107.777
  AMP: 1.0

DAC_DATA: DAC-ADC_AD7734-AD5791 (COM5)
DAC_CONV_TIME: 500
SAMPLING: 0.1
AVGS: 100

SWEEPS: 1

V_GATE_CH: 1
DAC_IN_CH:
- 6
- 7

V_GATE_I: -1.0
V_GATE_F: 1.0
V_GATE_STEPS: 100

